sonar.projectKey=FilipIvanovic16_Integracija-razvoja-i-operative-u-informacionim-tehnologijama---Filip-Ivanovic-IT52-2022
sonar.organization=filipivanovic16

sonar.sources=shared/src/main,services/auth-service/src/main,services/catalog-service/src/main,services/order-service/src/main,services/payment-service/src/main,services/api-gateway/src/main,services/notification-service/src/main,frontend/src
sonar.tests=services/auth-service/src/test,services/catalog-service/src/test,services/order-service/src/test,services/payment-service/src/test,services/api-gateway/src/test,services/notification-service/src/test,frontend/src
sonar.test.inclusions=**/*Test.java,**/*IT.java,**/*.test.js,**/*.test.jsx

sonar.java.binaries=shared/target/classes,services/auth-service/target/classes,services/catalog-service/target/classes,services/order-service/target/classes,services/payment-service/target/classes,services/api-gateway/target/classes,services/notification-service/target/classes
sonar.coverage.jacoco.xmlReportPaths=shared/target/site/jacoco/jacoco.xml,services/auth-service/target/site/jacoco/jacoco.xml,services/catalog-service/target/site/jacoco/jacoco.xml,services/order-service/target/site/jacoco/jacoco.xml,services/payment-service/target/site/jacoco/jacoco.xml,services/api-gateway/target/site/jacoco/jacoco.xml,services/notification-service/target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**,**/dist/**,**/node_modules/**,shared/src/main/**/generated/**
sonar.java.source=17
