CREATE TABLE brands (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)  NOT NULL,
    country     VARCHAR(80),
    description VARCHAR(1000),
    logo_url    VARCHAR(500),
    CONSTRAINT uk_brands_name UNIQUE (name)
);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE watches (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(150)   NOT NULL,
    reference_number    VARCHAR(80)    NOT NULL,
    brand_id            BIGINT         NOT NULL REFERENCES brands (id),
    category_id         BIGINT         NOT NULL REFERENCES categories (id),
    description         VARCHAR(2000),
    price               NUMERIC(12,2)  NOT NULL,
    stock_quantity      INTEGER        NOT NULL DEFAULT 0,
    movement            VARCHAR(20),
    gender              VARCHAR(10),
    case_diameter_mm    INTEGER,
    water_resistancem   INTEGER,
    image_url           VARCHAR(500),
    watch_condition     VARCHAR(20),
    documentation       VARCHAR(20),
    material            VARCHAR(80),
    active              BOOLEAN        NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_watches_reference_number UNIQUE (reference_number)
);

CREATE TABLE watch_images (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    watch_id    BIGINT        NOT NULL REFERENCES watches (id),
    url         VARCHAR(1000) NOT NULL,
    sort_order  INTEGER       NOT NULL DEFAULT 0
);

CREATE INDEX idx_watches_brand_id ON watches (brand_id);
CREATE INDEX idx_watches_category_id ON watches (category_id);
CREATE INDEX idx_watch_images_watch_id ON watch_images (watch_id);
