CREATE TABLE orders (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number        VARCHAR(40)   NOT NULL,
    user_id             BIGINT        NOT NULL,
    customer_email      VARCHAR(160)  NOT NULL,
    customer_name       VARCHAR(160)  NOT NULL,
    status              VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    total_amount        NUMERIC(12,2) NOT NULL DEFAULT 0,
    shipping_street     VARCHAR(200),
    shipping_city       VARCHAR(100),
    shipping_postal_code VARCHAR(20),
    shipping_country    VARCHAR(80),
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_orders_order_number UNIQUE (order_number)
);

CREATE TABLE order_items (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT        NOT NULL REFERENCES orders (id),
    watch_id          BIGINT        NOT NULL,
    watch_name        VARCHAR(150)  NOT NULL,
    reference_number  VARCHAR(80)   NOT NULL,
    quantity          INTEGER       NOT NULL,
    unit_price        NUMERIC(12,2) NOT NULL,
    line_total        NUMERIC(12,2) NOT NULL
);

CREATE TABLE wishlist_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT    NOT NULL,
    watch_id   BIGINT    NOT NULL,
    added_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_wishlist_user_watch UNIQUE (user_id, watch_id)
);

CREATE INDEX idx_orders_user_id ON orders (user_id);
CREATE INDEX idx_order_items_order_id ON order_items (order_id);
CREATE INDEX idx_wishlist_items_user_id ON wishlist_items (user_id);
