CREATE TABLE payments (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                    BIGINT        NOT NULL,
    order_number                VARCHAR(40)   NOT NULL,
    stripe_payment_intent_id    VARCHAR(100),
    stripe_event_id             VARCHAR(100),
    amount                      NUMERIC(12,2) NOT NULL,
    currency                    VARCHAR(3)    NOT NULL DEFAULT 'EUR',
    status                      VARCHAR(30)   NOT NULL DEFAULT 'REQUIRES_PAYMENT',
    customer_email              VARCHAR(160),
    customer_name               VARCHAR(160),
    created_at                  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at                     TIMESTAMP,
    CONSTRAINT uk_payments_stripe_payment_intent_id UNIQUE (stripe_payment_intent_id)
);

CREATE INDEX idx_payments_order_id ON payments (order_id);
